/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import classes.Aluno;
import classes.Curso;
import classes.Enfase;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Map;
import javax.swing.JOptionPane;
import persistencia.ManipulacaoArquivo;

/**
 *
 * @author puc
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private ManipulacaoArquivo crud = null;
    Map<String, Aluno> arvoreAluno = null;
    Map<Integer, Enfase> arvoreEnfase = null;
    Map<Integer, Curso> arvoreCurso = null;
    
    /**
     * Creates new form Tela
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            crud = new ManipulacaoArquivo();
            arvoreAluno = crud.getDadosAlunos();
            arvoreEnfase = crud.getDadosEnfase();
            arvoreCurso = crud.getDadosCurso();
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, erro);
        }
        WindowClosingEventHandler();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }
    
    
    
    private void WindowClosingEventHandler(){
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int resposta = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja fechar?","Confirmação", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION){
                    try{
                        crud.atualizarBancoDeDados(arvoreAluno, arvoreEnfase, arvoreCurso);
                        dispose();
                    }catch(Exception erro){
                        JOptionPane.showMessageDialog(null, erro);
                    }
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_GerenciarEnfases = new javax.swing.JButton();
        jButton_GerenciarAlunos = new javax.swing.JButton();
        jButton_GerenciarCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel1.setText("CRUD de Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton_GerenciarEnfases.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_GerenciarEnfases.setText("Gerenciar Enfases");
        jButton_GerenciarEnfases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GerenciarEnfasesActionPerformed(evt);
            }
        });

        jButton_GerenciarAlunos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_GerenciarAlunos.setText("Gerenciar Alunos");
        jButton_GerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GerenciarAlunosActionPerformed(evt);
            }
        });

        jButton_GerenciarCursos.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton_GerenciarCursos.setText("Gerenciar Cursos");
        jButton_GerenciarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GerenciarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton_GerenciarAlunos)
                .addGap(18, 18, 18)
                .addComponent(jButton_GerenciarEnfases)
                .addGap(18, 18, 18)
                .addComponent(jButton_GerenciarCursos)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_GerenciarEnfases, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GerenciarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_GerenciarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GerenciarAlunosActionPerformed
        // TODO add your handling code here:
        try {
            TelaAluno telaIncluir = new TelaAluno(arvoreAluno, arvoreEnfase, arvoreCurso);
            telaIncluir.setVisible(true);
            telaIncluir.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jButton_GerenciarAlunosActionPerformed

    private void jButton_GerenciarEnfasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GerenciarEnfasesActionPerformed
        // TODO add your handling code here:
        try {
            TelaEnfase telaEnfase = new TelaEnfase(arvoreEnfase);
            telaEnfase.setVisible(true);
            telaEnfase.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jButton_GerenciarEnfasesActionPerformed

    private void jButton_GerenciarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GerenciarCursosActionPerformed
        // TODO add your handling code here:
        try {
            TelaCurso telaCurso = new TelaCurso(arvoreCurso);
            telaCurso.setVisible(true);
            telaCurso.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jButton_GerenciarCursosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GerenciarAlunos;
    private javax.swing.JButton jButton_GerenciarCursos;
    private javax.swing.JButton jButton_GerenciarEnfases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
