/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import modelos.classes.Professor;

/**
 *
 * @author lusra
 */
public class Buscar extends javax.swing.JFrame {
    private MainUI mainUI;
    /**
     * Creates new form Buscar
     */
    public Buscar(MainUI mainUI) {
        initComponents();
        this.mainUI = mainUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1_busca = new javax.swing.JTextField();
        jButton1_BUSCAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Matricula:");

        jButton1_BUSCAR.setText("BUSCAR");
        jButton1_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BUSCARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_BUSCAR)
                    .addComponent(jTextField1_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BUSCARActionPerformed
        int valor = Integer.parseInt(jTextField1_busca.getText().toUpperCase());
        try {
            // Cria um mapa temporário para armazenar o resultado da busca
            Map<Integer, Professor> resultadoBusca = new TreeMap<>();

            // Percorre o mapa principal
            Iterator<Map.Entry<Integer, Professor>> lista = mainUI.mapa.entrySet().iterator();
            while (lista.hasNext()) {
                Map.Entry<Integer, Professor> entry = lista.next();
                Professor novoProf = entry.getValue();
                if (novoProf.getMatricula() == valor) {
                    resultadoBusca.put(novoProf.getMatricula(), novoProf);
                }
            }

            // Verifica se há resultados e os exibe
            if (!resultadoBusca.isEmpty()) {
                mainUI.listar_Dados(resultadoBusca.entrySet().iterator());
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Nenhum professor encontrado com a matrícula: " + valor,
                    "Busca", 
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1_BUSCARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_BUSCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1_busca;
    // End of variables declaration//GEN-END:variables
}
