/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import modelos.classes.Professor;
import telas.MainUI;
/**
 *
 * @author lusra
 */
public class Excluir extends javax.swing.JFrame {
    private MainUI mainUI;
    /**
     * Creates new form Excluir
     */
    public Excluir(MainUI mainUI) {
        initComponents();
        this.mainUI = mainUI;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1_excluir = new javax.swing.JTextField();
        jButton1_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Excluir:");

        jButton1_excluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1_excluir.setText("EXCLUIR");
        jButton1_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1_excluir)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1_excluir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_excluirActionPerformed
        int valor = Integer.parseInt(jTextField1_excluir.getText().toUpperCase());

        try {
            Iterator<Map.Entry<Integer, Professor>> lista = mainUI.mapa.entrySet().iterator();
            boolean encontrado = false;

            while (lista.hasNext()) {
                Map.Entry<Integer, Professor> entry = lista.next();
                if (entry.getKey() == valor) {
                    lista.remove();
                    encontrado = true;
                    JOptionPane.showMessageDialog(this, 
                        "Professor excluído com sucesso!", 
                        "Exclusão", 
                        JOptionPane.INFORMATION_MESSAGE
                    );
                }
            }

            // Verifica se a matrícula foi encontrada
            if (!encontrado) {
                JOptionPane.showMessageDialog(this, 
                    "Nenhum professor encontrado com a matrícula: " + valor,
                    "Busca", 
                    JOptionPane.WARNING_MESSAGE
                );
            } else {
                mainUI.listar_Dados(mainUI.mapa.entrySet().iterator());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_jButton1_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_excluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1_excluir;
    // End of variables declaration//GEN-END:variables
}
