/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelos.classes.ConjuntoProfessores;
import modelos.classes.Professor;
import persistencia.ManipulacaoArq;

/**
 *
 * @author lusra
 */
public class MainUI extends javax.swing.JFrame {

    ConjuntoProfessores professores = null;
    /**
     * Creates new form NewJFrame
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jTextField1_matricula.setEnabled(false);
        this.jTextField2_nome.setEnabled(false);
        this.jTextField3_materia.setEnabled(false);
        this.jComboBox1_graduacao.setEnabled(false);
        this.jComboBox2_contrato.setEnabled(false);
        try {
            
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(rootPane,"ERRO CRIACAO DO CONJUNTO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1_Logo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_incluir = new javax.swing.JButton();
        jButton6_alterar = new javax.swing.JButton();
        jButton8_excluir = new javax.swing.JButton();
        jButton3_explorar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_matricula = new javax.swing.JTextField();
        jTextField2_nome = new javax.swing.JTextField();
        jTextField3_materia = new javax.swing.JTextField();
        jComboBox1_graduacao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2_contrato = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setForeground(new java.awt.Color(102, 102, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Escola", "Graduação", "Contrato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jLabel1_Logo.setText("LOGO");

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TABELA DOCENTE");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jButton1_incluir.setBackground(new java.awt.Color(204, 255, 255));
        jButton1_incluir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1_incluir.setForeground(new java.awt.Color(87, 83, 55));
        jButton1_incluir.setText("INCLUIR ");
        jButton1_incluir.setBorderPainted(false);
        jButton1_incluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1_incluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_incluirActionPerformed(evt);
            }
        });

        jButton6_alterar.setBackground(new java.awt.Color(204, 255, 255));
        jButton6_alterar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton6_alterar.setForeground(new java.awt.Color(87, 83, 55));
        jButton6_alterar.setText("ALTERAR ");
        jButton6_alterar.setBorderPainted(false);
        jButton6_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6_alterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_alterarActionPerformed(evt);
            }
        });

        jButton8_excluir.setBackground(new java.awt.Color(204, 255, 255));
        jButton8_excluir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton8_excluir.setForeground(new java.awt.Color(87, 83, 55));
        jButton8_excluir.setText("EXCLUIR ");
        jButton8_excluir.setBorderPainted(false);
        jButton8_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8_excluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton8_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8_excluirActionPerformed(evt);
            }
        });

        jButton3_explorar.setBackground(new java.awt.Color(204, 255, 255));
        jButton3_explorar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton3_explorar.setForeground(new java.awt.Color(87, 83, 55));
        jButton3_explorar.setText("EXPLORAR");
        jButton3_explorar.setBorderPainted(false);
        jButton3_explorar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3_explorar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3_explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_explorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3_explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setText("Graduação:");

        jLabel5.setText("Contrato:");

        jComboBox1_graduacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doutor(a)", "Mestre(a)", "Bacharelado", "Pós Doutor(a)" }));

        jLabel1.setLabelFor(jTextField2_nome);
        jLabel1.setText("Nome:");

        jComboBox2_contrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "Horista" }));

        jLabel2.setLabelFor(jTextField1_matricula);
        jLabel2.setText("Matrícula:");

        jLabel3.setLabelFor(jTextField3_materia);
        jLabel3.setText("Matéria:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1_graduacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2_contrato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField3_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1_graduacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(506, 506, 506))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(276, 276, 276)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_incluirActionPerformed
        // TODO add your handling code here:
        try {
            int matricula = Integer.parseInt(jTextField1_matricula.getText());
            String nome = jTextField2_nome.getText();
            String escola = jTextField3_materia.getText();
            String titulacao = (String)(jComboBox1_graduacao.getSelectedItem());
            String contrato = (String)(jComboBox2_contrato.getSelectedItem());
            Professor objetoProfessor = new Professor(matricula, nome, escola, titulacao, contrato);
            professores.incluir(objetoProfessor);
            Professor prof[] = professores.listagemDeProfessores();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String[] saida = new String[9];
            saida[0] = prof[professores.getIndiceOcupacao()].getMatricula() + "";
            saida[1] = prof[professores.getIndiceOcupacao()].getNome()+ "";
            saida[2] = prof[professores.getIndiceOcupacao()].getEscola()+ "";
            saida[3] = prof[professores.getIndiceOcupacao()].getTitulacao()+ "";
            saida[4] = prof[professores.getIndiceOcupacao()].getTipoContrato()+ "";
            model.addRow(saida);
          } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
          }
    }//GEN-LAST:event_jButton1_incluirActionPerformed

    private void jButton8_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_excluirActionPerformed
        // TODO add your handling code here:
        try {
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int i = jTable1.getSelectedRow();
            int confirmacao = JOptionPane.showConfirmDialog(rootPane, "Deseja mesmo Excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if(confirmacao == JOptionPane.YES_OPTION){
                if(i >= 0){
                    professores.excluir(Integer.parseInt((String) model.getValueAt(i, 0)));
                    model.setNumRows(0);
                    Professor[] vetorProf = professores.listagemDeProfessores();

                    // Apaga todos os elementos na tabela e atualiza
                    for (int iterador = 0; iterador <= professores.getIndiceOcupacao(); iterador++) {
                        String[] saida = new String[5];
                        saida[0] = vetorProf[iterador].getMatricula() + "";
                        saida[1] = vetorProf[iterador].getNome();
                        saida[2] = vetorProf[iterador].getEscola();
                        saida[3] = vetorProf[iterador].getTitulacao();
                        saida[4] = vetorProf[iterador].getTipoContrato();
                        model.addRow(saida);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada!");
                }
            }
        } catch (Exception erro) {
          JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_jButton8_excluirActionPerformed

    private void jButton3_explorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_explorarActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "text", "csv", "txt");
            fc.setFileFilter(filter);
            int returnVal = fc.showOpenDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File arquivo = fc.getSelectedFile();
                ManipulacaoArq arq = new ManipulacaoArq(arquivo.toString());
                professores = arq.obterListaProfessores();
                this.jTextField1_matricula.setEnabled(true);
                this.jTextField2_nome.setEnabled(true);
                this.jTextField3_materia.setEnabled(true);
                this.jComboBox1_graduacao.setEnabled(true);
                this.jComboBox2_contrato.setEnabled(true);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                Professor[] vetorProf = professores.listagemDeProfessores();

                // Apaga todos os elementos na tabela e atualiza
                for (int iterador = 0; iterador < professores.getIndiceOcupacao(); iterador++) {
                    String[] saida = new String[9];
                    saida[0] = vetorProf[iterador].getMatricula() + "";
                    saida[1] = vetorProf[iterador].getNome() + "";
                    saida[2] = vetorProf[iterador].getEscola() + "";
                    saida[3] = vetorProf[iterador].getTitulacao() + "";
                    saida[4] = vetorProf[iterador].getTipoContrato() + "";
                    model.addRow(saida);
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton3_explorarActionPerformed
    // TODO add your handling code here:
    // TODO add your handling code here:

    private void jButton6_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_alterarActionPerformed
        // TODO add your handling code here:
        try {
            int matricula = Integer.parseInt(jTextField1_matricula.getText());
            String nome = jTextField2_nome.getText();
            String escola = jTextField3_materia.getText();
            String titulacao = (String)(jComboBox1_graduacao.getSelectedItem());
            String contrato = (String)(jComboBox2_contrato.getSelectedItem());
            Professor objetoProfessor = new Professor(matricula, nome, escola, titulacao, contrato);
            professores.alterar(objetoProfessor);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
                Professor[] vetorProf = professores.listagemDeProfessores();

                // Apaga todos os elementos na tabela e atualiza
                    for (int iterador = 0; iterador <= professores.getIndiceOcupacao(); iterador++) {
                        String[] saida = new String[5];
                        saida[0] = vetorProf[iterador].getMatricula() + "";
                        saida[1] = vetorProf[iterador].getNome();
                        saida[2] = vetorProf[iterador].getEscola();
                        saida[3] = vetorProf[iterador].getTitulacao();
                        saida[4] = vetorProf[iterador].getTipoContrato();
                        model.addRow(saida);
                    }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }//GEN-LAST:event_jButton6_alterarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_incluir;
    private javax.swing.JButton jButton3_explorar;
    private javax.swing.JButton jButton6_alterar;
    private javax.swing.JButton jButton8_excluir;
    private javax.swing.JComboBox<String> jComboBox1_graduacao;
    private javax.swing.JComboBox<String> jComboBox2_contrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Logo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_matricula;
    private javax.swing.JTextField jTextField2_nome;
    private javax.swing.JTextField jTextField3_materia;
    // End of variables declaration//GEN-END:variables
}
